export const FETCH_FILES_SUCCESS = "/app/FILES/FETCH_FILES_SUCCESS";
export const SAVE_FILE_SUCCESS = "/app/FILES/SAVE_FILE_SUCCESS";
export const DELETE_FILE_SUCCESS = "/app/FILES/DELETE_FILE_SUCCESS";
