export const BLUETOOTH_STARTED = '/app/BLUETOOTH/BLUETOOTH_STARTED';
export const CONNECT_DEVICE_SUCCESS = '/app/BLUETOOTH/CONNECT_DEVICE_SUCCESS';
export const DISCONNECT_DEVICE_SUCCESS = '/app/BLUETOOTH/DISCONNECT_DEVICE_SUCCESS';
