export const FETCH_INVESTIGATIONS = "/app/DOWNLOAD/FETCH_INVESTIGATIONS";
export const FETCH_INVESTIGATIONS_SUCCESS = "/app/DOWNLOAD/FETCH_INVESTIGATIONS_SUCCESS";
export const FETCH_INVESTIGATIONS_FAILED = "/app/DOWNLOAD/FETCH_INVESTIGATIONS_FAILED";
